frameworkVersion: '3'
useDotenv: true

service: hello-world

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    sourcemap: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: development
  region: ap-southeast-2
  environment:
    NODE_OPTIONS: --enable-source-maps
  iam:
    role:
      statements:

package:
  individually: true

functions:
  hello-world:
    handler: src/hello-world.handleHelloWorld
    events:
      - httpApi:
          method: GET
          path: /
